### ISSUE TITLE
Atom process keeps getting "Killed"

### ISSUE THREAD

**Issue by impiyush** [tvdboom/ATOM#21]
I am trying to run atom-ml with LR and LSVM on a big dataset. The full dataset has about 350K rows, and about the same number of cols (NLP problem, with tf-idf on the words)

The problem is that with a very small dataset it all works fine, but as soon as the size of the dataset increases, the ATOM process gets killed. I noticed the memory consumption (using top), and it keeps increasing. At one point the process was using about 40GB of memory and kept increasing.

Question: How to better work with very large datasets using atom-ml?

**Using "top"**
![Screenshot from using "top"](https://user-images.githubusercontent.com/3663894/147696140-55a431cd-fdba-42be-9576-373939ca5523.png)

**ATOM process Killed, with only 50K rows dataset**
![ATOM process Killed, with only 50K rows dataset](https://user-images.githubusercontent.com/3663894/147696982-ec58a984-3f07-4558-a442-af77f287c737.png)

**Comment by tvdboom** [comment]
Hi. I’m currently on holidays so I can not do any debugging until the 14th.

ATOM makes two copies of the dataset (see https://tvdboom.github.io/ATOM/user_guide/data_management/#memory-considerations) so this means that there will be three copies in memory at initialization (the third being the original). This could be the reason that much memory is used and why the process dies. Can you check the memory size of your dataset? How much is it? What format is it: pandas dataframe, numpy array or sparse matrix?

Unfortunately, there is not really a way to work efficiently with such large datasets at this point. I am working on a memory-efficient implementation using sparse matrices (right now you can input them but they are always converted to full arrays internally) for next release.

**Comment by tvdboom** [comment]
Update: ATOM's newest release (v4.11.0) has full support for sparse matrices and has improvements in memory usage. If your dataset is a sparse matrix, it should work fine
