### ISSUE TITLE
How can I save model with feature_generation

### ISSUE THREAD

**Issue by chuwenhao123** [tvdboom/ATOM#29]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://tvdboom.github.io/ATOM/latest/contributing/).
- [X] The documentation does not mention anything about my problem.
- [X] There are no open or closed issues that are related to my problem.

### Description

I tried feature generation with atom, and I met this error when I wanted to save model .

PicklingError: Can't pickle <class 'featuretools.primitives.base.transform_primitive_base.sqrt'>: it's not found as featuretools.primitives.base.transform_primitive_base.sqrt

![image](https://user-images.githubusercontent.com/51478550/157183164-ad37a8eb-b867-4153-9498-1eb379b7d73f.png)

### Python and package version

- Python: 3.7.4
- ATOM: 4.12.0

**Comment by chuwenhao123** [comment]
```
import numpy as np
from atom import ATOMRegressor
import joblib

atom = ATOMRegressor((x_train, y_train), (x_val,y_val), verbose=2, random_state=2021)
atom.warnings = False
# Pipeline
atom.run('CatB',metric=["MAE","r2"]) 

# DFS
atom.branch = "dfs"
# Create 50 new features using DFS
atom.feature_generation("dfs", n_features=20, operators=["add", "sub","mul","sqrt", "log","sin","cos"])  # add, sub, mul, div, sqrt, log, sin, cos, tan.
atom.run("CatB_dfs")

# GFG
atom.branch = "gfg"
# Create new features using Genetic Programming
atom.feature_generation(strategy='GFG', n_features=20,generations=30,random_state=2021)
# We can see the feature's fitness and description through the genetic_features attribute
atom.genetic_features
# Fit the model again
atom.run("CatB_gfg")

atom.save("atom_cbr_chap.pkl",save_data=False)
# joblib.dump(atom,"atom_cbr_chap.pkl")
```

**Comment by chuwenhao123** [comment]
Hi,I meet another porblem when I use LGB Regressor:
Exception encountered while running the LGB model. Removing model from pipeline. 
ImportError: cannot import name 'log_evaluation' from 'lightgbm.callback' (/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/lightgbm/callback.py)

![image](https://user-images.githubusercontent.com/51478550/157254313-44dc4d30-e62e-45b1-973a-f7c79e09d0b1.png)

**Comment by tvdboom** [comment]
Hi. The first issue seems indeed like a bug. I'll have a look at it tomorrow and come back to you. The LightGBM issue probably occurs because you have an older version of the library installed. Try updating it running: `pip install -U lightgbm`.

**Comment by tvdboom** [comment]
The fix for the saving bug is implemented and pushed to the development branch. Thanks for pointing it out. It will be available with next release. If you can't wait (this may take up to a month since the latest release was quite recently), you can download the updated package directly from git running pip install git+https://github.com/tvdboom/ATOM.git@development.

**Comment by chuwenhao123** [comment]
Thank you for your help

**Comment by chuwenhao123** [comment]
I met another problem:

AttributeError: Can't get attribute 'sqrt' on <module 'featuretools.primitives.base.transform_primitive_base' from '/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/featuretools/primitives/base/transform_primitive_base.py'>

![image](https://user-images.githubusercontent.com/51478550/157584189-f2071b08-a77b-4c88-a53d-4a86eab74987.png)

**Comment by chuwenhao123** [comment]
I saved the model with save_data=False, but when I reloaded the file this error occurred
